---
# vars file for nginx-proxy
domain_name: www.mycompanyname.ru
gitlab: gitlab.mycompanyname.ru
grafana: grafana.mycompanyname.ru
prometheus: prometheus.mycompanyname.ru
alertmanager: alertmanager.mycompanyname.ru
letsencrypt_email: example@mycompanyname.ru
