- hosts: mycompanyname.ru
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - nginx-proxy

- hosts: db01.mycompanyname.ru
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - mysql

- hosts: db02.mycompanyname.ru
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - mysql