### hostname from inventoryfile
- hosts: nginx
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - nginx-proxy

- hosts: mysql
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - mysql

- hosts: wordpress
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - wordpress

- hosts: gitlab
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - gitlab

- hosts: runner
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - gitlab-runner