### hostname from inventoryfile
- hosts: nginx
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - nginx-proxy

- hosts: mysql #db01.mycompanyname.ru
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - mysql

- hosts: wordpress #app.mycompanyname.ru
  become: yes
  become_user: root
  remote_user: ubuntu
  roles:
  - wordpress